image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  artifacts:
    paths:
      - 'src/UI/Web/bin/Debug/netcoreapp2.1/publish'
  script:
    - 'cd src/UI/Web'
    - 'dotnet restore'
    - 'dotnet build '
    - 'dotnet publish'

test_job:
  stage: test
  script:
    - 'dotnet test tests/UnitTests'
    - 'dotnet test tests/IntegrationTests'
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  artifacts:
    paths:
      - 'src/UI/Web/bin/Debug/netcoreapp2.1/publish'
  script:
  - 'cd src/UI/Web/bin/Debug/netcoreapp2.1/publish'
  - 'cf login -a https://api.run.pivotal.io -u $CF_USERNAME -p $CF_PASSWORD -s eshop'
  - 'cf push -f manifest-Web.yml'
  dependencies:
    - build_job
    - test_job
  
