image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  artifacts:
    paths:
      - 'src/WebRazorPages/bin/Debug/netcoreapp2.1/publish'
#  before_script:
#    - 'C:\NuGet\nuget.exe restore' 
  script:
    - 'cd src/WebRazorPages'
    - 'dotnet restore'
    - 'dotnet build '
    - 'dotnet publish'

test_job:
  stage: test
  script:
    - 'dotnet test tests/UnitTests'
    - 'dotnet test tests/IntegrationTests'
    - 'dotnet test tests/FunctionalTests'
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  artifacts:
    paths:
      - 'src/WebRazorPages/bin/Debug/netcoreapp2.1/publish'
  script:
  - 'cd src/WebRazorPages/bin/Debug/netcoreapp2.1/publish'
  - 'cf login -a https://api.run.pivotal.io -u $CF_USERNAME -p $CF_PASSWORD -s Development'
  - 'cf push eshoponpcf-gitlab-ci -m 256M -k 512M'
  dependencies:
    - build_job
    - test_job
  