image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

build_job_web:
  stage: build
  artifacts:
    paths:
      - 'src/UI/Web/bin/Debug/netcoreapp2.1/publish'
  script:
    - |
      if git diff HEAD~ --name-only|grep src/UI/; then
        pwd
        cd src/UI/Web
        dotnet restore
        dotnet build
        dotnet publish
      else
        echo "Skipping Web build coz no change was detected in the Web project"
        exit -1
      fi;

test_job_web:
  stage: test
  script:
    - 'dotnet test tests/UnitTests'
    - 'dotnet test tests/IntegrationTests' 
  dependencies:
    - build_job_web

deploy_job_web:
  stage: deploy
  artifacts:
    paths:
      - 'src/UI/Web/bin/Debug/netcoreapp2.1/publish'
  script:
    - |
      if git diff HEAD~ --name-only|grep src/UI/; then
        'cf login -a https://api.run.pivotal.io -u $CF_USERNAME -p $CF_PASSWORD -s eshop'
        'cf push -f manifest-Web.yml'
      fi;
  dependencies:
    - build_job_web
    - test_job_web