version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  eureka:
    image: netflixoss/eureka:1.3.1

#  catalog.api:
#    image: eshop/catalog.api:${TAG:-latest}
#    build:
#      context: .
#      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
#    depends_on:
#      - sql.data
#      - rabbitmq
#      - eureka
