version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    

  rabbitmq:
    ports:
      - "15672:15672" 
      - "5672:5672"   

  eureka:
    ports:
      - "8762:8762"

#  catalog.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://0.0.0.0:80
#      - SqlServer__credentials__ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=sql.data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word}
#      - PicBaseUrl=${ESHOP_AZURE_STORAGE_CATALOG_URL:-http://localhost:5101/api/v1/c/catalog/items/[0]/pic/}   #Local: You need to open your local dev-machine firewall at range 5100-5110.  
#      - rabbitmq__client__uri=amqp://guest:guest@localhost:5672/
#      - AzureStorageAccountName=${ESHOP_AZURE_STORAGE_CATALOG_NAME}
#      - AzureStorageAccountKey=${ESHOP_AZURE_STORAGE_CATALOG_KEY}
#      - UseCustomizationData=True
#      - AzureServiceBusEnabled=False
#      - AzureStorageEnabled=False
#      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
#      - OrchestratorType=${ORCHESTRATOR_TYPE}
#    ports:
#      - "5101:80"   # Important: In a production environment your should remove the external port (5101) kept here for microservice debugging purposes. 
#                    # The API Gateway redirects and access through the internal port (80).