version: '3.4'

services:
  cache:
    image: redis
    command: redis-server --requirepass testPassword
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: eshop/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - eurekareg
      - rabbitmq    

  eurekareg:
    image: steeltoeoss/eurekaserver
