version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
     - ACCEPT_EULA=TRUE

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
     -  "5672:5672"
    
  ordering.api:
    image: eshop/ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile   
   
    depends_on:
      - sql.data
      - rabbitmq

  ordering.backgroundtasks:
    image: eshop/ordering.backgroundtasks:${TAG:-latest}
    build:
      context: .
      dockerfile: Ordering.BackgroundTasks/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

 